# Generated by Django 4.2.2 on 2023-12-16 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=63)),
                ("price", models.IntegerField()),
                ("phone", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("number_of_guests", models.IntegerField()),
                ("date", models.DateField()),
                ("price", models.IntegerField()),
                (
                    "contractors",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="agency.contractor"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate"),
                            ("wedding", "Wedding"),
                            ("first_date", "First Date"),
                            ("stag", "Stag"),
                            ("girls_party", "Girls Party"),
                            ("working_meeting", "Working Meeting"),
                            ("birthday", "Birthday"),
                            ("christening_of_a_child", "Christening of a child"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("adult", models.BooleanField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Men"), ("female", "Women")], max_length=6
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="HallOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("black", "Black"),
                            ("pink", "Pink"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("gray", "Gray"),
                            ("mafia", "Mafia"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
                ("position", models.CharField(max_length=63)),
                (
                    "events_organized",
                    models.ManyToManyField(
                        blank=True, related_name="organizers", to="agency.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agency.event"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="agency.eventtype"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="guests",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="event_guests", to="agency.guest"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agency.style"
            ),
        ),
        migrations.CreateModel(
            name="EventHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("maximum_number_of_guests", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="hall_options",
                        to="agency.halloption",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "city")},
            },
        ),
    ]
