# Generated by Django 4.2.2 on 2023-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="guests",
            field=models.ManyToManyField(
                blank=True, related_name="event_guests", to="agency.guest"
            ),
        ),
        migrations.AlterField(
            model_name="eventhall",
            name="options",
            field=models.ManyToManyField(
                blank=True, related_name="hall_options", to="agency.halloption"
            ),
        ),
    ]
