# Generated by Django 4.2.2 on 2023-12-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "Agency"},
        ),
    ]
