# Generated by Django 4.2.2 on 2023-12-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_event_guests_alter_eventhall_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="phone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="organizer",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizer",
            name="phone",
            field=models.CharField(default=2, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventhall",
            name="phone",
            field=models.CharField(max_length=13),
        ),
    ]
