# Generated by Django 4.2.2 on 2023-12-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_guest_email_guest_phone_organizer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="style",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("pink", "Pink"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("gray", "Gray"),
                    ("mafia", "Mafia"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Style",
        ),
    ]
